// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hR4UwPFYv3gaa10n4-LYETNJALwPQGQ',
    appId: '1:35501714833:android:aa4101b787f1492948be30',
    messagingSenderId: '35501714833',
    projectId: 'hob-it',
    storageBucket: 'hob-it.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfTAmaMHfXsxh3jii9p_ZWGpPR87CD47g',
    appId: '1:35501714833:ios:d9ace4eb2348bdc648be30',
    messagingSenderId: '35501714833',
    projectId: 'hob-it',
    storageBucket: 'hob-it.firebasestorage.app',
    iosBundleId: 'com.vgv.hobIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfTAmaMHfXsxh3jii9p_ZWGpPR87CD47g',
    appId: '1:35501714833:ios:d9ace4eb2348bdc648be30',
    messagingSenderId: '35501714833',
    projectId: 'hob-it',
    storageBucket: 'hob-it.firebasestorage.app',
    iosBundleId: 'com.vgv.hobIt',
  );
}
