name: hobby_repository
description: Owns hobby domain models and composes a HobbyApi data source.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  equatable: ^2.0.8
  hobby_api:
    path: ../hobby_api
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.8.0
  very_good_analysis: ^7.0.0