name: in_memory_hobby_api
description: An in-memory HobbyApi implementation for development.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  hobby_api:
    path: ../hobby_api

dev_dependencies:
  very_good_analysis: ^7.0.0